# -*- coding: utf-8 -*-
"""Weather Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOsmnAzgW4DDRM0ztoufQj4305NfZwHA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

data = pd.read_csv("DailyDelhiClimateTrain.csv")
print(data.head())

print(data.describe())

print(data.info())

plt.style.use("fivethirtyeight")
sns.set_palette("Set2")

figure = px.line(data, x="date",
                 y="meantemp",
                 title='Mean Temperature in Delhi Over the Years')
figure.show()

figure = px.line(data, x="date",
                 y="humidity",
                 title='Humidity in Delhi Over the Years')
figure.show()

figure = px.line(data, x="date",
                 y="wind_speed",
                 title='Wind Speed in Delhi Over the Years')
figure.show()

figure = px.scatter(data_frame = data, x="humidity",
                    y="meantemp", size="meantemp",
                    trendline="ols",
                    title = "Relationship Between Temperature and Humidity")
figure.show()

data["date"] = pd.to_datetime(data["date"], format = '%Y-%m-%d')
data['year'] = data['date'].dt.year
data["month"] = data["date"].dt.month
print(data.head())

plt.style.use('fivethirtyeight')
plt.figure(figsize=(15, 10))
plt.title("Temperature Change in Delhi Over the Years")
sns.lineplot(data = data, x='month', y='meantemp', hue='year')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
sns.heatmap(data[['meantemp', 'humidity', 'wind_speed']].corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Matrix")
plt.show()

"""ANOMALY DETECTION USING Z-SCORE"""

import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore

# Calculate z-scores
data["temp_zscore"] = zscore(data["meantemp"])
anomalies = data[np.abs(data["temp_zscore"]) > 2]  # Customize threshold

# Set the style
sns.set(style="whitegrid")

# Plot anomalies
plt.figure(figsize=(12, 6))

# Plot mean temperature as a line plot
plt.plot(data["date"], data["meantemp"], label="Mean Temp", color='#1f77b4', linewidth=2)

# Plot anomalies as red dots
plt.scatter(anomalies["date"], anomalies["meantemp"], color='red', label="Anomaly", s=80, zorder=5)

# Title and labels with enhanced font
plt.title("Temperature Anomalies (Z-Score > 2)", fontsize=16, fontweight='bold', color='darkblue')
plt.xlabel("Date", fontsize=12, fontweight='bold')
plt.ylabel("Temperature (°C)", fontsize=12, fontweight='bold')

# Customize ticks
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(fontsize=10)

# Add gridlines and improve legend
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(fontsize=12, loc='upper left')

# Show plot
plt.tight_layout()  # Ensure everything fits without overlap
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
import matplotlib.pyplot as plt

# Set date as index for decomposition
data.set_index("date", inplace=True)

# Perform decomposition
result = seasonal_decompose(data["meantemp"], model='additive', period=365)

# Plot
fig, axes = plt.subplots(4, 1, figsize=(12, 8), sharex=True, dpi=100)
components = [result.observed, result.trend, result.seasonal, result.resid]
titles = ['Observed', 'Trend', 'Seasonal', 'Residual']

# Style settings
line_colors = ['#007acc', '#33a02c', '#ff7f0e', '#6a3d9a']
plt.subplots_adjust(hspace=0.4)

for ax, comp, title, color in zip(axes, components, titles, line_colors):
    comp.plot(ax=ax, linewidth=1.5, color=color)
    ax.set_title(title, fontsize=11, fontweight='bold')
    ax.grid(alpha=0.3)
    ax.tick_params(axis='x', labelrotation=0)
    ax.spines[['top', 'right']].set_visible(False)

fig.suptitle("Seasonal Decomposition of Mean Temperature", fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.show()

# Reset index if needed later
data.reset_index(inplace=True)

!pip install prophet

forecast_data = data.rename(columns = {"date": "ds",
                                       "meantemp": "y"})
print(forecast_data)

from prophet import Prophet
from prophet.plot import plot_plotly, plot_components_plotly
model = Prophet()
model.fit(forecast_data)
forecasts = model.make_future_dataframe(periods=365)
predictions = model.predict(forecasts)
plot_plotly(model, predictions)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Actual vs predicted comparison
actual = forecast_data['y'][-365:].reset_index(drop=True)
predicted = predictions['yhat'][-365:].reset_index(drop=True)

mae = mean_absolute_error(actual, predicted)
rmse = np.sqrt(mean_squared_error(actual, predicted))

print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")

# Prepare data with regressors
forecast_data = data.rename(columns={"date": "ds", "meantemp": "y"})
forecast_data["humidity"] = data["humidity"]
forecast_data["wind_speed"] = data["wind_speed"]

# Train-test split if you want to evaluate (optional)
# forecast_data = forecast_data[forecast_data['ds'] < "2016-01-01"]

from prophet import Prophet

model = Prophet()
model.add_regressor('humidity')
model.add_regressor('wind_speed')

model.fit(forecast_data)

future = model.make_future_dataframe(periods=365)
# Fill in regressor values for future (use last known values)
future["humidity"] = data["humidity"].iloc[-1]
future["wind_speed"] = data["wind_speed"].iloc[-1]

forecast = model.predict(future)

from prophet.plot import plot_plotly, plot_components_plotly

plot_plotly(model, forecast)
plot_components_plotly(model, forecast)